version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
      - ./backend/logs:/tmp

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  web3-signer:
    build:
      context: ./web3-signer
    ports:
      - "8081:8080"
    volumes:
      - ./web3-signer:/www

  redis:
    image: "redis:alpine"